server:
  port: 32051
spring:
  application:
    name: usercenter
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/

mybatis:
  mapper-locations: classpath:/mapper/*.xml