### apollo 配置
app.id: usercenter
# set apollo meta server address, adjust to actual address if necessary
apollo.meta: http://localhost:8080


###
server:
  port: 32052
spring:
  application:
    name: usercenter
  profiles:
    active: dev
###
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/