server:
  port: 32051
spring:
  application:
    name: usercenter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/


logging:
  level:
    com.xiao.dao.mapper: DEBUG