server:
  port: 32051
spring:
  profiles:
    include: dao
  application:
    name: usercenter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/