spring:
  profiles:
    include: dao
  application:
    name: project-01
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 32022
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/