spring:
  application:
    name: project-01
server:
  port: 32022
eureka:
  client:
    service-url:
      defaultZone: http://localhost:32011/eureka/,http://localhost:32012/eureka/

logging:
  level:
    com.xiao.dao.mapper: DEBUG